### ISSUE TITLE
Alch Blocker

### ISSUE THREAD

**Issue by Valteritis** [robrichardson13/alch-blocker#10]
Hi!
For some time this hasn't been working for me. Any ideas why?

**Comment by RedSparr0w** [comment]
Could you upload an image of your blacklist/inventory with high alch?

**Comment by Valteritis** [comment]
Valters

**Comment by robrichardson13** [comment]
Looks like there are 2 known plugin conflicts:

- Remaining Casts

**Comment by Valteritis** [comment]
I had "instant inventory", turning it off fixed this.
Thank you!

Valters
