### ISSUE TITLE
Add toggle for "only show items in list"

### ISSUE THREAD

**Issue by Eyeownyew** [robrichardson13/alch-blocker#2]
This would effectively invert the logic; i.e. toggle "only show items in list", list contains `yew longbow`, only show yew longbow in inventory when alching

**Comment by robrichardson13** [comment]
Added in v1.1, waiting for approval now: https://github.com/runelite/plugin-hub/pull/3826

**Comment by robrichardson13** [comment]
Re-opening until update is merged.
