### ISSUE TITLE
wild card support

### ISSUE THREAD

**Issue by broderickBW** [robrichardson13/alch-blocker#4]
wild card support would be nice, so that 'prayer potion*' would cover all doses of potion

'prayer potion*' = 'prayer potion(4), prayer potion(3),prayer potion(2),prayer potion(1)'

even *potion* would cover almost every potion type and all of their doses

**Comment by robrichardson13** [comment]
Added in v1.1, waiting for approval now: https://github.com/runelite/plugin-hub/pull/3826

**Comment by robrichardson13** [comment]
Re-opening until update is merged.
