### ISSUE TITLE
New method of hiding items interfaces poorly with other plugins

### ISSUE THREAD

**Issue by zdunbrack** [robrichardson13/alch-blocker#5]
In update 1.1, the way that items were hidden by this plugin changed. As a result, overlays by plugins such as "Clue Steps", "Weapon Charges", "Inventory Tags", and "Rune Pouch" show even when the item is hidden.

![Screenshot_20230205_160229](https://user-images.githubusercontent.com/23144957/216845606-0c523671-c4ad-4e11-8cfd-f8b08ccb8f6d.png)

This is more distracting than the old behavior where the items would be hidden altogether.

**Comment by robrichardson13** [comment]
Fix was just merged in, closing this.
