### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by Bree757** [robrichardson13/alch-blocker#7]
Just downloaded the plugin from the hub and it just doesn't seem to work. Nothing is hidden when I press the high alch icon.

**Comment by robrichardson13** [comment]
Do you also have this plugin? I’ve seen that both plugins are conflicting. https://github.com/elgbar/instant-inventory

To confirm if any other plugins are conflicting, you can turn everything else off (specifically any inventory based plugins and try again).

**Comment by Bree757** [comment]
Nope, I don't have instant inventory BUT I just had a friend test it and his works fine, it's definitely a plugin conflict. I'll do some testing and post which plugin is the culprit. Thanks!

**Comment by Bree757** [comment]
Sorry I was a little busy today. I got around to testing and I found it. It's "Remaining Casts" plugin in case anyone else has this issue.
